### ISSUE TITLE
Build for Nano PC T4

### ISSUE THREAD

**Issue by BillGatesMS** [hjc4869/armbian-build#1]
Hello......could you please explain in a few words where i have to copy which files exactly, because i just dont get it.......completely lost the overview.....

here are the folders i got on my hdd

**### Overview**

![main](https://user-images.githubusercontent.com/40524804/41812068-33762bee-771c-11e8-9400-97967fb3a744.png)

**### build-folder**

![build](https://user-images.githubusercontent.com/40524804/41812071-42dfbcc6-771c-11e8-8b40-45f4e34a1d34.png)

**### rockchip-folder**

![rokchip](https://user-images.githubusercontent.com/40524804/41812073-51e89d14-771c-11e8-8165-f92a85cf22f9.png)

**### firefly-rk3399-folder**

![firefly](https://user-images.githubusercontent.com/40524804/41812075-5b6115e2-771c-11e8-84f1-f65728841c0a.png)

**### Every folder has different content........what i have to  do?**
### **Which files i have to add to which folder?**

![1494687541137415936](https://user-images.githubusercontent.com/40524804/41812164-f8d2487c-771d-11e8-9836-0f98ba87700c.jpg)

**Comment by BillGatesMS** [comment]
Thanks mate!

**Comment by hjc4869** [comment]
Checkout the development branch, there will be "firefly.conf" kernel configuration.
There are two WIP boards added: firefly-rk3399 and nanopct4, you can either select them in the menu, or ./compile.sh BOARD=nanopct4

**Comment by diglos** [comment]
Hi @hjc4869,

first of all, thank you for your work :-)

I'm running into some trouble building the NanoPC-t4 Image (tried with your last commit from 2 hours ago). Compiling stops at u-boot stage with the following error:
```
Text Base (SYS_TEXT_BASE) [] (NEW) 
Error in reading or end of file.
```
It seems to me that SYS_TEXT_BASE variable is not assigned. Firefly-rk3399 image builds fine on the other hand.

I'm on a Vagrant environment using Ubuntu Bionic (I tried on Xenial with the same result).

Thanks!

**Comment by hjc4869** [comment]
@diglos That's because the nanopi4_defconfig is for the old u-boot, and recently I've updated the u-boot to mainline, so it's currently broken.

I'll try to fix it anyway.

**Comment by diglos** [comment]
Ok, thanks!

**Comment by hjc4869** [comment]
https://github.com/hjc4869/armbian-build/commit/7d9ff262bc90424ec74e1d578e2cf73e68f2fa08
This should fix the u-boot compilation.

**Comment by diglos** [comment]
It works now. Thanks!!!

**Comment by hanshaze** [comment]
yes, thanks for sharing your knowledge and work with us @hjc4869 :) Thumbs up!
Think i got it --->
![bildschirmfoto vom 2018-06-27 00-35-19](https://user-images.githubusercontent.com/17994050/41943077-4e71761e-79a2-11e8-80fb-7c7ceba09543.png)

One last question, ok ^^
How do i handle these files? I have expected an img or iso....

Best regards

**Comment by BillGatesMS** [comment]
Sheesh
